function createhggroup(Parent1, XData1, YData1, XData2, YData2)
%CREATEHGGROUP(PARENT1, XDATA1, YDATA1, XDATA2, YDATA2)
%  PARENT1:  hggroup parent
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata

%  Auto-generated by MATLAB on 06-Dec-2018 22:04:48

% Create hggroup
hggroup1 = hggroup('Parent',Parent1,'DisplayName','PID');

% Create line
line(XData1,YData1,'Parent',hggroup1,'Tag','Curves','LineWidth',1,...
    'Color',[0 1 0]);

% Create line
line(XData2,YData2,'Visible','off','Parent',hggroup1,'HitTest','off',...
    'Tag','StemLines',...
    'LineWidth',2,...
    'Color',[0 1 0]);

