function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, XData6, YData6, XData7, YData7)
%CREATEFIGURE(XDATA1, YDATA1, XDATA2, YDATA2, XDATA3, YDATA3, XDATA4, YDATA4, XDATA5, YDATA5, XDATA6, YDATA6, XDATA7, YDATA7)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  XDATA4:  line xdata
%  YDATA4:  line ydata
%  XDATA5:  line xdata
%  YDATA5:  line ydata
%  XDATA6:  line xdata
%  YDATA6:  line ydata
%  XDATA7:  line xdata
%  YDATA7:  line ydata

%  Auto-generated by MATLAB on 06-Dec-2018 22:21:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'YColor',[0.4 0.4 0.4],...
    'XColor',[0.4 0.4 0.4],...
    'Position',[0.138784773060029 0.11 0.766215226939971 0.784742813918306]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 20]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1.2]);
box(axes1,'on');
hold(axes1,'on');

% Create line
line(XData1,YData1,'Visible','off','Parent',axes1);

% Create hggroup
hggroup1 = hggroup('Parent',axes1,'DisplayName','PI');

% Create line
line(XData2,YData2,'Parent',hggroup1,'Tag','Curves','LineWidth',2,...
    'Color',[0 0.447 0.741]);

% Create line
line(XData3,YData3,'Visible','off','Parent',hggroup1,'HitTest','off',...
    'Tag','StemLines',...
    'LineWidth',2,...
    'Color',[0 0.447 0.741]);

% Create hggroup
hggroup2 = hggroup('Parent',axes1,'DisplayName','PD');

% Create line
line(XData4,YData4,'Parent',hggroup2,'Tag','Curves','LineWidth',2,...
    'Color',[0.85 0.325 0.098]);

% Create line
line(XData5,YData5,'Visible','off','Parent',hggroup2,'HitTest','off',...
    'Tag','StemLines',...
    'LineWidth',2,...
    'Color',[0.85 0.325 0.098]);

% Create hggroup
hggroup3 = hggroup('Parent',axes1,'DisplayName','PID');

% Create line
line(XData6,YData6,'Parent',hggroup3,'Tag','Curves','LineWidth',2,...
    'Color',[0 1 0]);

% Create line
line(XData7,YData7,'Visible','off','Parent',hggroup3,'HitTest','off',...
    'Tag','StemLines',...
    'LineWidth',2,...
    'Color',[0 1 0]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.83943387076964 0.782148294192157 0.060761346409471 0.105395862010772],...
    'FontSize',12);

% Create ylabel
ylabel('Amplitude','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontSize',11,...
    'Visible','on');

% Create xlabel
xlabel('Time (seconds)','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontSize',11,...
    'Visible','on');

% Create title
title('Step Response','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',11);

